ROTOR_WIRINGS={
    "I"     :"EKMFLGDQVZNTOWYHXUSPAIBRCJ",
    "II"    :"AJDKSIRUXBLHWTMCQGZNPYFVOE",
    "III"   :"BDFHJLCPRTXVZNYEIWGAKMUSQO",
    "IV"    :"ESOVPZJAYQUIRHXLNFTGKDCMWB",
    "V"     :"VZBRGITYUPSDNHLXAWMJQOFECK",
    "VI"    :"JPGVOUMFYQBENHZRDKASXLICTW",
    "VII"   :"NZJHGRCXMYSWBOUFAIVLPEKQDT",
    "VIII"  :"FKQHTLXOCBJSPDZRAMEWNIUYGV"
}

ROTOR_NOTCHES={
    "I"     :"Q",
    "II"    :"E",
    "III"   :"V",
    "IV"    :"J",
    "V"     :"Z",
    "VI"    :"MZ",
    "VII"   :"MZ",
    "VIII"  :"MZ"
}

REFLECTOR_WIRINGS={
    "A"     :"EJMZALYXVBWFCRQUONTSPIKHGD",
    "B"     :"YRUHQSLDPXNGOKMIEBFZCWVJAT",
    "C"     :"FVPJIAOYEDRZXWGCTKUQSBNMHL"
}